# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a clean Node.js image to run the application
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the build output and necessary files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json /app/package-lock.json ./

# Set environment variable for the Ticketmaster API key
# (This can also be set at runtime using `docker run -e TICKETMASTER_API_KEY=your_api_key`)
ENV TICKETMASTER_API_KEY=your-api-key-here

# Install production dependencies
RUN npm ci --omit=dev

# Set the entry point to run the server
ENTRYPOINT ["node", "build/index.js"]
